# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [5]:
print(np.__version__)

1.16.4


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [12]:
arr=np.zeros((4,4))
print(arr.size*arr.itemsize)

128


 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
np.add?



 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
print(np.linspace(10,49,20))

[10.         12.05263158 14.10526316 16.15789474 18.21052632 20.26315789
 22.31578947 24.36842105 26.42105263 28.47368421 30.52631579 32.57894737
 34.63157895 36.68421053 38.73684211 40.78947368 42.84210526 44.89473684
 46.94736842 49.        ]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [19]:
#arr=np.flipud(ARRAY_NAME)
arr=np.array([1,2,3,4])
arr=arr[::-1]
print(arr)

[4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [23]:
arr=np.array([1,2,0,0,4,0])
for i in range(0,6):
    if(arr[i]!=0):
        print(i)

0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
#a=np.identity(3,dtype=int)
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
print(np.random.randn(3,3,3))

[[[ 1.28735148 -0.468467    0.52484797]
  [ 0.39959208 -0.24221469  0.34871582]
  [-1.3555941   0.62200615 -0.79435957]]

 [[ 0.39501395  0.82894685 -0.45033631]
  [-1.50758475 -1.1888691   1.51291904]
  [ 1.78796676 -0.97399469  0.39717811]]

 [[-0.99579668  1.54260725 -0.85700202]
  [-0.78825269  1.66411583  0.28762538]
  [-0.08582251  1.41927969  0.75582927]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
arr=np.random.random((10,10))
print(arr)
print(np.max(arr))
print(np.min(arr))

[[0.33640036 0.39845866 0.01390026 0.16385851 0.80797698 0.58404772
  0.20066494 0.38277978 0.24635265 0.35064014]
 [0.15153483 0.05375164 0.40637294 0.51073279 0.32624837 0.30783642
  0.10099375 0.93360413 0.3426513  0.55657475]
 [0.98834661 0.39765686 0.59645146 0.65147877 0.81247395 0.69001123
  0.80432013 0.86929814 0.23253137 0.661901  ]
 [0.45775115 0.28291963 0.1948677  0.65633664 0.36927128 0.92954009
  0.5237522  0.69930876 0.87908957 0.22156371]
 [0.97740164 0.53863354 0.15228369 0.74403958 0.39625644 0.78873232
  0.93292882 0.56569644 0.6585217  0.69560195]
 [0.98116466 0.41068047 0.4619576  0.43181704 0.6446126  0.54202014
  0.15139591 0.12002557 0.87371451 0.6397023 ]
 [0.20139389 0.41954694 0.67699871 0.74930886 0.85647152 0.78990233
  0.21714408 0.76426802 0.4414119  0.85120314]
 [0.83768578 0.52565227 0.15422381 0.19380236 0.84761514 0.95588258
  0.80311319 0.08974896 0.19496567 0.84129705]
 [0.79904287 0.11439956 0.33036348 0.62584008 0.40724449 0.1023903
  0.54895242 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [32]:
arr=np.random.random(30)
print(np.mean(arr))
print(arr)

0.4669610977732443
[0.6085502  0.2602499  0.90807633 0.65287124 0.41555722 0.43399142
 0.85158789 0.63366519 0.56911195 0.77558617 0.35897359 0.11802218
 0.89268096 0.59276367 0.85848367 0.42226458 0.02246909 0.19135271
 0.24860418 0.43824146 0.67603548 0.38577455 0.29321184 0.01022242
 0.10131024 0.31607612 0.51260394 0.88359254 0.2156993  0.36120292]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [35]:
arr=np.ones((3,3))
arr[1][1]=0
print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [7]:
a=np.ones((2,2))
a=np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(a)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [9]:
#Did'nt understood

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
arr=np.zeros((5,5))
arr=np.tril([1,2,3,4,5],0)
print(arr)

[[1 0 0 0 0]
 [1 2 0 0 0]
 [1 2 3 0 0]
 [1 2 3 4 0]
 [1 2 3 4 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
#did'nt understood

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
(2,1,3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
#could'nt understand

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [16]:
#could'nt understand


Object `np.normalize` not found.


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
#could'nt understand

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [17]:
arr1=np.random.randn(5,3)
arr2=np.random.randn(3,2)
print(np.dot(arr1,arr2))

[[-0.36309568 -1.73394849]
 [-0.51530166 -0.43301088]
 [-0.62132588 -1.28881365]
 [ 0.33305683  1.69900612]
 [ 1.34809951  1.86703988]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(0,10):
    if(i>2and i<7):
        print(arr[i]*-1)
    else:
        print(arr[i])

1
2
3
-4
-5
-6
-7
8
9
10


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
10
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [14]:
arr1=np.array([10,20,40,50])
arr2=np.array([10,30,80])
print(np.intersect1d(arr1,arr2))

[10]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

NameError: name 'warnings' is not defined

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#No,Beacuse sqrt cannot operate on negative values. 

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [16]:
import datetime 
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2019-10-18
Today :  2019-10-19
Tomorrow :  2019-10-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [19]:
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))


July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [21]:
vector=np.array([10,9,8,7,6,5,4,3,2,1])
print(np.sort(vector))

[ 1  2  3  4  5  6  7  8  9 10]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

True


#### 43. Make an array immutable (read-only) (★★☆)

In [32]:
arr=np.array([1,2,3,4,4])
arr=tuple(arr)
print(arr)

(1, 2, 3, 4, 4)


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [36]:
arr=np.array([23,45,78,34,23,56,86,34,23,123])
arr[i]=arr.max(axis=0)
arr[i]=0
print(arr)

[23 45 78 34 23 56 86 34 23  0]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [3]:
arr=np.array([2,45,67,6778,345,62355])
print(arr)

[    2    45    67  6778   345 62355]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)